In [109]:
import pandas as pd
import geopandas as gpd

In [110]:
df = pd.read_csv('/home/emmanuelgonzalez/Gantry_fieldbook_2020_Revised_Irr_TRT.csv', dtype='str').set_index('Plot')

In [111]:
df

,Field,Species,Experiment,Revised_irrigation_treatment,Range,Column,Rep,Type,SbEMS_ID,PI_accession,Harvest_Id,PI_check,Unnamed: 13,Unnamed: 14
Plot,,,,,,,,,,,,,,
0101,south,Sorghum bicolor,EMS_pop,WW,01,01,1,border,NaN,BTx_623,NaN,NaN,NaN,NaN
0102,south,Sorghum bicolor,EMS_pop,WW,01,02,1,border,NaN,BTx_623,NaN,NaN,NaN,NaN
0103,south,Sorghum bicolor,EMS_pop,WW,01,03,1,border,NaN,BTx_623,NaN,NaN,NaN,NaN
0104,south,Sorghum bicolor,EMS_pop,WW,01,04,1,border,NaN,BTx_623,NaN,NaN,NaN,NaN
0105,south,Sorghum bicolor,EMS_pop,WW,01,05,1,border,NaN,BTx_623,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5428,south,Sorghum bicolor,EMS_pop,WL,54,28,1,border,NaN,BTx_623,NaN,NaN,NaN,NaN
5429,south,Sorghum bicolor,EMS_pop,WL,54,29,1,border,NaN,BTx_623,NaN,NaN,NaN,NaN
5430,south,Sorghum bicolor,EMS_pop,WL,54,30,1,border,NaN,BTx_623,NaN,NaN,NaN,NaN
5431,south,Sorghum bicolor,EMS_pop,WL,54,31,1,border,NaN,BTx_623,NaN,NaN,NaN,NaN
5432,south,Sorghum bicolor,EMS_pop,WL,54,32,1,border,NaN,BTx_623,NaN,NaN,NaN,NaN

In [112]:
gj = gpd.read_file('/home/emmanuelgonzalez/season11_multi_latlon.geojson')

In [113]:
gj['genotype'] = None

for i, row in gj.iterrows():
    #row['genotype'] = None
    plot = row['ID']
    row_df = df.loc[plot]
    geno = row_df['PI_accession']
    #print(plot, geno)
    gj['genotype'][i] = str(geno)

<ipython-input-113-de71bf04b98f>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gj['genotype'][i] = str(geno)

In [114]:
gj.to_file('/home/emmanuelgonzalez/season11_multi_latlon_geno.geojson', driver='GeoJSON')